#!/usr/bin/env sh
# ******************************************************************************
# This file is part of the wp-awesome package.
#
# File: .githooks/pre-commit
#
# Author: Christian Denat
#
# Created on: 2026-10-07
# Last modified: 2026-10-07
#
# Copyright © 2026 Christian Denat
# ******************************************************************************

set -eu
bun scripts/vendor-agent-links.mjs prepare
trap 'bun scripts/vendor-agent-links.mjs restore' EXIT
bun run headers:update
